version: '3'

services:
  app:
    container_name: app
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - noobium-net
  db:
    container_name: db
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: 'noobium-test'
      MYSQL_ROOT_PASSWORD: 'nopassword'
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - noobium-net
    env_file:
      - .env
    ports:
      - 3306

volumes:
  db-data:

networks:
  noobium-net:
